const members = [
    // GENERATION 0 JP
    { name: "Tokino Sora", gen: 0, genID: "JP", debutDate: new Date("2017-09-07"), endDate: null,
    youtube: "https://www.youtube.com/channel/UCp6993wxpyDPHUpavwDFqgg", twitter: "https://twitter.com/tokino_sora",
    hololiveEN: "https://en.hololive.tv/portfolio/items/433553", hololiveJP: "https://www.hololive.tv/portfolio/items/336222" },
    { lastName: "Roboco", gen: 0, genID: "JP", debutDate: new Date("2018-03-04"), endDate: null,
    youtube: "https://www.youtube.com/channel/UCDqI2jOz0weumE8s7paEk6g", twitter: "https://twitter.com/robocosan",
    hololiveEN: "https://en.hololive.tv/portfolio/items/433579", hololiveJP: "https://www.hololive.tv/portfolio/items/336223" },
    { lastName: "Sakura Miko", gen: 0, genID: "JP", debutDate: new Date("2018-08-01"), endDate: null,
    youtube: "https://www.youtube.com/channel/UC-hM6YJuNYVAmUWxeIr9FeA", twitter: "https://twitter.com/sakuramiko35",
    hololiveEN: "https://en.hololive.tv/portfolio/items/433578", hololiveJP: "https://www.hololive.tv/portfolio/items/336371" },
    { lastName: "Hoshimachi Suisei", gen: 0, genID: "JP", debutDate: new Date("2018-03-22"), endDate: null,
    youtube: "https://www.youtube.com/channel/UC5CwaMl1eIgY8h02uZw7u8A", twitter: "https://twitter.com/suisei_hosimati",
    hololiveEN: "https://en.hololive.tv/portfolio/items/433550", hololiveJP: "https://www.hololive.tv/portfolio/items/345947" },
    { lastName: "AZKi", gen: 0, genID: "JP", debutDate: new Date("2018-11-15"), endDate: null,
    youtube: "https://www.hololive.tv/portfolio/items/345947", twitter: "https://twitter.com/AZKi_VDiVA",
    hololiveEN: "https://en.hololive.tv/portfolio/items/433588", hololiveJP: "https://www.hololive.tv/portfolio/items/336226" },

    // GENERATION 1 JP
    { lastName: "Yozora Mel", gen: 1, genID: "JP", debutDate: new Date("2018-05-13"), endDate: null,
    youtube: "https://www.youtube.com/channel/UCD8HOxPs4Xvsm8H0ZxXGiBw", twitter: "https://twitter.com/yozoramel",
    hololiveEN: "https://en.hololive.tv/portfolio/items/433549", hololiveJP: "https://www.hololive.tv/portfolio/items/336404" },
    { lastName: "Shirakami Fubuki", gen: 1, genID: "JP", debutDate: new Date("2018-06-01"), endDate: null,
    youtube: "https://www.youtube.com/channel/UCdn5BQ06XqgXoAxIhbqw5Rg", twitter: "https://twitter.com/shirakamifubuki",
    hololiveEN: "https://en.hololive.tv/portfolio/items/433587", hololiveJP: "https://www.hololive.tv/portfolio/items/336378" },
    { lastName: "Natsuiro Matsuri", gen: 1, genID: "JP", debutDate: new Date("2018-06-01"), endDate: null,
    youtube: "https://www.youtube.com/channel/UCQ0UDLQCjY0rmuxCDE38FGg", twitter: "https://twitter.com/natsuiromatsuri",
    hololiveEN: "https://en.hololive.tv/portfolio/items/433575", hololiveJP: "https://www.hololive.tv/portfolio/items/336381" },
    { lastName: "Aki Rosenthal", gen: 1, genID: "JP", debutDate: new Date("2018-06-07"), endDate: null,
    youtube: "https://www.youtube.com/channel/UCFTLzh12_nrtzqBPsTCqenA", twitter: "https://twitter.com/akirosenthal",
    hololiveEN: "https://en.hololive.tv/portfolio/items/433574", hololiveJP: "https://www.hololive.tv/portfolio/items/336382" },
    { lastName: "Akai Haato", gen: 1, genID: "JP", debutDate: new Date("2018-06-02"), endDate: null,
    youtube: "https://www.youtube.com/channel/UC1CfXB_kRs3C-zaeTG3oGyg", twitter: "https://twitter.com/akaihaato",
    hololiveEN: "https://en.hololive.tv/portfolio/items/433551", hololiveJP: "https://www.hololive.tv/portfolio/items/336380" },
    { lastName: "Hitomi Chris", gen: 1, genID: "JP", debutDate: new Date("2018-06-03"), endDate: new Date("2018-06-25"),
    youtube: null, twitter: "https://twitter.com/hitomikurisu",
    hololiveEN: null, hololiveJP: null },

    // GENERATION 2 JP
    { lastName: "Minato Aqua", gen: 2, genID: "JP", debutDate: new Date("2018-08-08"), endDate: null,
    youtube: "https://www.youtube.com/channel/UC1opHUrw8rvnsadT-iGp7Cg", twitter: "https://twitter.com/minatoaqua",
    hololiveEN: "https://en.hololive.tv/portfolio/items/433565", hololiveJP: "https://www.hololive.tv/portfolio/items/336383" },
    { lastName: "Murasaki Shion", gen: 2, genID: "JP", debutDate: new Date("2018-08-17"), endDate: null,
    youtube: "https://www.youtube.com/channel/UCXTpFs_3PqI41qX2d9tL2Rw", twitter: "https://twitter.com/murasakishionch",
    hololiveEN: "https://en.hololive.tv/portfolio/items/433577", hololiveJP: "https://www.hololive.tv/portfolio/items/336387" },
    { lastName: "Nakiri Ayame", gen: 2, genID: "JP", debutDate: new Date("2018-09-03"), endDate: null,
    youtube: "https://www.youtube.com/channel/UC7fk0CB07ly8oSl0aqKkqFg", twitter: "https://twitter.com/nakiriayame",
    hololiveEN: "https://en.hololive.tv/portfolio/items/433583", hololiveJP: "https://www.hololive.tv/portfolio/items/336384" },
    { lastName: "Yuzuki Choco", gen: 2, genID: "JP", debutDate: new Date("2018-09-05"), endDate: null,
    youtube: "https://www.youtube.com/channel/UC1suqwovbL1kzsoaZgFZLKg", twitter: "https://twitter.com/yuzukichococh",
    hololiveEN: "https://en.hololive.tv/portfolio/items/433552", hololiveJP: "https://www.hololive.tv/portfolio/items/336386" },
    { lastName: "Oozora Subaru", gen: 2, genID: "JP", debutDate: new Date("2018-09-16"), endDate: null,
    youtube: "https://www.youtube.com/channel/UCvzGlP9oQwU--Y0r9id_jnA", twitter: "https://twitter.com/oozorasubaru",
    hololiveEN: "https://en.hololive.tv/portfolio/items/433593", hololiveJP: "https://www.hololive.tv/portfolio/items/336385" },

    // GENERATION 1 EN
    { lastName: "Mori Calliope", gen: 1, genID: "EN", debutDate: new Date("2020-09-12"), endDate: null,
    youtube: "https://www.youtube.com/channel/UCL_qhgtOy0dy1Agp8vkySQg", twitter: "https://twitter.com/moricalliope",
    hololiveEN: "https://en.hololive.tv/portfolio/items/584527", hololiveJP: "https://www.hololive.tv/portfolio/items/584535" },
    { lastName: "Takanashi Kiara", gen: 1, genID: "EN", debutDate: new Date("2020-09-12"), endDate: null,
    youtube: "https://www.youtube.com/channel/UCHsx4Hqa-1ORjQTh9TYDhww", twitter: "https://twitter.com/takanashikiara",
    hololiveEN: "https://en.hololive.tv/portfolio/items/584528", hololiveJP: "https://www.hololive.tv/portfolio/items/584540" },
    { lastName: "Ninomae Ina'nis", gen: 1, genID: "EN", debutDate: new Date("2020-09-13"), endDate: null,
    youtube: "https://www.youtube.com/channel/UCMwGHR0BTZuLsmjY_NT5Pwg", twitter: "https://twitter.com/ninomaeinanis",
    hololiveEN: "https://en.hololive.tv/portfolio/items/584532", hololiveJP: "https://www.hololive.tv/portfolio/items/584542" },
    { lastName: "Gawr Gura", gen: 1, genID: "EN", debutDate: new Date("2020-09-13"), endDate: null,
    youtube: "https://www.youtube.com/channel/UCoSrY_IQQVpmIRZ9Xf-y93g", twitter: "https://twitter.com/gawrgura",
    hololiveEN: "https://en.hololive.tv/portfolio/items/584533", hololiveJP: "https://www.hololive.tv/portfolio/items/584544" },
    { lastName: "Watson Amelia", gen: 1, genID: "EN", debutDate: new Date("2020-09-13"), endDate: null,
    youtube: "https://www.youtube.com/channel/UCyl1z3jo3XHR1riLFKG5UAg", twitter: "https://twitter.com/watsonameliaEN",
    hololiveEN: "https://en.hololive.tv/portfolio/items/584534", hololiveJP: "https://www.hololive.tv/portfolio/items/584546" }
]